### ISSUE TITLE
Impl: groupByTypes

### ISSUE THREAD

**Issue by cptbtptp01** [cptbtptp01/ideation-accessibilty#18]

**Comment by cptbtptp01** [comment]
@z-q-ying  since i am currently working on clusterByType, maybe i should take this issue? just let me know, and feel free to assign to me!

just fyi, there might be some design changes for clusterByType's return type. will provide update in future PR once i implemented and tested!

**Comment by z-q-ying** [comment]
@cptbtptp01 Feel free to take this one if it makes more sense. If there further arises a timing issue feel free to assign back to me too! (Will unassign myself for now)
