### ISSUE TITLE
Impl: adjust frontend to reflect current json output from groupItems()

### ISSUE THREAD

**Issue by cptbtptp01** [cptbtptp01/ideation-accessibilty#32]

**Comment by cptbtptp01** [comment]
@z-q-ying just fyi, I will start update frontend part base on the json output. Current interface displays the raw json output. Should be an independent task!

**Comment by z-q-ying** [comment]
@cptbtptp01 yes yes, my goal is also to make the json output works so we can move things forward in Parallel.

@koolgax99 Feel free to test run the app (on sticker frame only unfortunately - other types still wip); trust this shall give a good flavor on the json output format which may be needed for the ChatGPT API?
