### ISSUE TITLE
Impl: real-time events notification

### ISSUE THREAD

**Issue by cptbtptp01** [cptbtptp01/ideation-accessibilty#5]
- Note: the current listeners in app.tsx are just starter code, feel free to remove!
- Refactor current notification related functions/code, e.g. remove from the app.tsx, consider to have a `notification.tsx`
- Real events can be further filtered as (idea proposed by @z-q-ying ):
  - user created empty items: this may not be considered worth to add to the notification
  - user created items with content: add to notification

**Comment by cptbtptp01** [comment]
Below are the ideas from our meeting:
1. Providing a result - e.g. "user created a [item]."
2. Collaboration events notification (to me, this kind of notification sounds more helpful from a low-vision user's standpoint):
   - User xx joined the board.
   -  User xx left the board.
   - 3 users are editing on the board.

@z-q-ying feel free to add your proposal, and @koolgax99 feel free to design the notification feature based on your decisions!

**Comment by koolgax99** [comment]
Reopening as this issue has still scope for improvement
