### ISSUE TITLE
Type error - array length property

### ISSUE THREAD

**Issue by z-q-ying** [cptbtptp01/ideation-accessibilty#63]
Issue raised by @koolgax99 

![image](https://github.com/cptbtptp01/ideation-accessibilty/assets/116849653/bf6810a8-3374-418d-af0e-6bab707306ad)

**Comment by koolgax99** [comment]
Do you guys have this issue as well? Btw I am running the `main` branch. Is that the appropriate branch?

**Comment by z-q-ying** [comment]
> Do you guys have this issue as well? Btw I am running the `main` branch. Is that the appropriate branch?

- Not really, up to PR #59 this shall works fine... but no worries this type of bug is easy to fix
- Typically the main version is the latest working version 
- May I suggest for the PRs,  wait for at least one of the reviewers to review and test before merging into main so that the main branch is always workings (though it may contain new bugs); e.g. #60 seems not working on my end (interface does not load, maybe it is not the latest version?) but as it is in main, I would have to fix bug on top of it which make things a bit more difficult... Thanks!
<img width="800" alt="image" src="https://github.com/cptbtptp01/ideation-accessibilty/assets/116849653/e17c40cb-7e53-466b-b45f-8229b1ef73a1">
